version: '3.2'
services:

  events-test-backend-1:
    image: node:16
    links:
      - mongo-db
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispass
      - APP_DATABASE_SECRET_URL=mongodb://mongo-db:27017
    networks:
      - app-network
    depends_on:
      - mongo-db
      - redis
    working_dir: /src
    volumes:
      - ./:/src
    command: bash -c "npm install && npm run start:dev"

  events-test-backend-2:
    image: node:16
    links:
      - mongo-db
      - redis
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispass
      - APP_DATABASE_SECRET_URL=mongodb://mongo-db:27017
    networks:
      - app-network
    depends_on:
      - mongo-db
      - redis
    working_dir: /src
    volumes:
      - ./:/src
    command: bash -c "npm install && npm run start:dev"

  mongo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  events-test-backend-1:
  events-test-backend-2:
  redis-data:
